admin_post_index:
    path:      /admin
    defaults:
        _controller: AppBundle:Post:index

admin_post_new:
    path:      /admin/new
    defaults:
        _controller: AppBundle:Post:new

admin_post_show:
    path:       /admin/show/{id}
    defaults:
        _controller: AppBundle:Post:show
    requirements:
        id: \d+

admin_post_edit:
    path:       /admin/edit/{id}
    defaults:
        _controller: AppBundle:Post:edit
    requirements:
        id: \d+

admin_post_delete:
    path:      admin/delete/{id}
    defaults:
        _controller: AppBundle:Post:delete
    requirements:
        id: \d+